services:  
  multi_robots:
    container_name: multi_robots
    build: 
      context: ..
      dockerfile: Docker/Dockerfile
    network_mode: "host"
    environment:
      - DISPLAY=host.docker.internal:0.0      
    stdin_open: true    # Keep stdin open for an interactive shell
    tty: true    
    command: ["/bin/bash"]
    #command: bash -c "source /opt/ros/jazzy/setup.bash && source /root/multi_robots_ws/install/setup.bash && ros2 launch multi_robots multi_robot_sim.launch.py"
    